language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: cp .travis.oasis _oasis && bash -ex .travis-opam.sh # && bash -ex .coveralls.sh
sudo: required
env:
  matrix:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
notifications:
  slack: xseng:ge9mYWGZZGFQPv3LsBnQeFCR
